# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json
services:
  cacheserver:
    image: chocolatefrappe/flutter-cacheserver:dev
    ports:
      - 36081:36081
    volumes:
      - type: volume
        source: cache
        target: /var/cache/flutter
    stop_grace_period: 5m
volumes:
  cache:
