# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json
services:
  flutter-cache-server:
    image: chocolatefrappe/flutter-cache-server:dev
    ports:
      - mode: ingress
        target: 36081
        published: 36081
        protocol: tcp
    volumes:
      - type: volume
        source: flutter-cache
        target: /var/lib/flutter
      - type: tmpfs
        target: /var/cache/nginx
    # stop_grace_period: 5m
    deploy:
      update_config:
        order: start-first
      rollback_config:
        order: start-first
volumes:
  flutter-cache:
