services:
  flutter-cache-server:
    image: chocolatefrappe/flutter-cache-server:dev
    ports:
      - mode: ingress
        target: 36080
        published: 36080
        protocol: tcp
    volumes:
      - type: volume
        source: flutter-cache
        target: /var/lib/flutter
    stop_grace_period: 5m
    restart: always
volumes:
  flutter-cache:
