services:
  cache-server:
    image: flutter-release-cache-server:dev
    ports:
      - 9876:80
    volumes:
      - type: volume
        source: cache
        target: /var/lib/flutter-release

volumes:
  cache:
