# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json
services:
  flutter:
    image: chocolatefrappe/flutter-cache-server:dev
    ports:
      - 36081:80
    volumes:
      - type: volume
        source: data
        target: /var/lib/flutter
    stop_grace_period: 1m
    deploy:
      update_config:
        order: start-first
      rollback_config:
        order: start-first
volumes:
  data:
